import React from 'react';

export const Disclaimer = ({ className = '' }) => (
  <div className={`mt-6 sm:mt-8 pt-4 sm:pt-6 border-t border-slate-200 ${className}`}>
    <p className="text-[12px] text-slate-500 leading-relaxed">
      Securities offered through LPL Financial, Member FINRA/SIPC. Investment advice offered through Miller Wealth Management, a Registered Investment Advisor and separate entity from LPL Financial.
    </p>
    <p className="text-[12px] text-slate-500 leading-relaxed mt-2 sm:mt-3">
      Past performance is no guarantee of future results. The projections or other information generated by this report regarding the likelihood of various investment outcomes are hypothetical in nature, do not reflect actual investment results, and are not guarantees of future results. The illustrations herein use return assumptions based on the asset classes to which the portfolio is allocated.
    </p>
  </div>
);
