import React, { useState } from 'react';
import { ChevronDown, ChevronUp, AlertTriangle } from 'lucide-react';

export const ImportantDisclosures = ({ className = '' }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className={`mt-6 sm:mt-8 pt-4 sm:pt-6 border-t border-slate-200 ${className}`}>
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between text-left group"
      >
        <span className="flex items-center gap-2 text-xs sm:text-sm font-bold text-slate-600">
          <AlertTriangle className="w-4 h-4 text-yellow-600" />
          Important Disclosures
        </span>
        {isExpanded ? (
          <ChevronUp className="w-4 h-4 text-slate-400 group-hover:text-slate-600" />
        ) : (
          <ChevronDown className="w-4 h-4 text-slate-400 group-hover:text-slate-600" />
        )}
      </button>

      {isExpanded && (
        <div className="mt-4 space-y-4 text-[12px] text-slate-500 leading-relaxed">
          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Broker-Dealer & Investment Advisor Disclosure</p>
            <p>
              Securities offered through LPL Financial, Member{' '}
              <a href="https://www.finra.org" target="_blank" rel="noopener noreferrer" className="underline hover:text-emerald-600">FINRA</a>/
              <a href="https://www.sipc.org" target="_blank" rel="noopener noreferrer" className="underline hover:text-emerald-600">SIPC</a>.
              Investment advice offered through Miller Wealth Management, a Registered Investment Advisor
              and separate entity from LPL Financial.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Hypothetical Projections</p>
            <p>
              The projections or other information generated by this tool regarding the likelihood of various
              investment outcomes are hypothetical in nature, do not reflect actual investment results, and
              are not guarantees of future results. Results may vary with each use and over time.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Past Performance</p>
            <p>
              Past performance is no guarantee of future results. The illustrations herein use return assumptions
              based on historical data and the asset classes to which the portfolio is allocated. Actual returns
              may be higher or lower than those shown.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Investment Risk</p>
            <p>
              All investments involve risk, including loss of principal. There is no guarantee that any investment
              strategy will achieve its objectives. Asset allocation and diversification do not ensure a profit
              or protect against a loss.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Monte Carlo Simulations</p>
            <p>
              Monte Carlo simulations are used to show how variations in rates of return each year can affect
              your results. The simulations do not predict the actual performance of any investment. Sequence
              of returns risk and market volatility can significantly impact actual outcomes.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Tax Considerations</p>
            <p>
              This analysis estimates the impact of income taxes on retirement withdrawals by assuming all
              portfolio assets are held in pre-tax retirement accounts (IRA/401k) and applying a 5% state
              income tax rate. Actual tax liability will depend on your specific account types, withdrawal
              strategy, and applicable tax laws, which are subject to change. Please consult a qualified
              tax professional regarding your specific situation.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Asset Location, Distribution Strategy & Tax Management</p>
            <p>
              The tax assumptions used in this illustration represent a simplified, conservative scenario.
              In practice, asset location (the placement of investments across taxable, tax-deferred, and
              tax-free accounts), distribution strategy (the order and timing of withdrawals from different
              account types), and proactive tax management (such as Roth conversions, tax-loss harvesting,
              and bracket management) could all have a meaningful impact on the after-tax outcome of your
              portfolio. A well-coordinated strategy across these areas may significantly improve your
              retirement sustainability beyond what is illustrated here.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Social Security</p>
            <p>
              Social Security benefit estimates are based on current law and your provided inputs. Actual
              benefits may differ. Social Security claiming strategies should be evaluated based on your
              individual circumstances, health considerations, and overall financial plan.
            </p>
          </div>

          <div>
            <p className="font-bold text-slate-600 text-[12px] mb-1">Not a Recommendation</p>
            <p>
              This tool is for educational purposes only and does not constitute a recommendation to buy or
              sell any security or adopt any investment strategy. You should consult with a qualified financial
              advisor before making any investment decisions.
            </p>
          </div>
        </div>
      )}

      {/* Always visible summary */}
      <p className="mt-3 text-[12px] text-slate-400">
        For educational purposes only. Not investment advice. Consult a financial professional before making decisions.
      </p>
    </div>
  );
};

export default ImportantDisclosures;
